version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    ports:
      - "8000:8000"

    depends_on:
      - db
    env_file:
      - ./.env  
    volumes:
      - ./backend/staticfiles:/app/staticfiles  # Mapping static files

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
      image: nginx:latest
      container_name: nginx_server
      restart: always
      ports:
        - "80:80"
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/staticfiles:/app/staticfiles 
      depends_on:
        - app

volumes:
    postgres_data:
    static_volume: 